### PR TITLE
Issue #15 Updating barito app statuses as provisioning / bootstrapping run through

### PR DESCRIPTION
**Pull request by giosakti**

### CODE REVIEW

**Comment by ajeygore** [comment]
I see two issues, are we using Figaro? sorry I did not check gems. Also I see too big function names.

**Comment by giosakti** [comment]
@ajeygore yes we already using figaro since the beginning (only for dev), do you have any concern?
and can you pinpoint some of the function names?

**Comment by ajeygore** [comment]
Initialise and  provision_instances is way too big that what it should be.

**Comment by ajeygore** [comment]
merging it now, but we should refactor this once it comes to highlight again.

**Pull request merged**
