### PR TITLE
For issue #12

### PR DESCRIPTION
**Pull request by opan**

### CODE REVIEW

**Comment by ajeygore** [comment]
Can you please resolve conflicts?

**Comment by opan** [comment]
@ajeygore Okay

**Comment by opan** [comment]
Codacy checks unsuccessful is because `rubocop.yml` is want us to put a comma in every last item on the array but codacy don't want that. So I leave it as is for now.

**Comment by ajeygore** [comment]
Sid, can you please resolve this?

**Comment by tagnotfound** [comment]
@opan you can edit the rubocop file to disable this and fix the build.

**Comment by opan** [comment]
@tagnotfound Okay

**Comment by opan** [comment]
@tagnotfound Will check this again after break fasting.

**Pull request closed without merging**
